# Generated by Django 5.2.1 on 2025-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=14, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
